const coreExecutiveData = [
	{
		president: {
			title: "President",
			president: "Grace Naa Adaku-Aryequaye",
			level: "500",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/president.jpg",
		},
		vice: {
			title: "Vice President",
			president: "Godwin Nupkezah",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/vice.jpg",
		},
		gsec: {
			title: "General Secretary",
			president: "Princess Amo",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/gsec.jpg",
		},
		agsec: {
			title: "Vice General Secretary",
			president: "Priscilla Eugenia",
			level: "300",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/agsec.jpg",
		},
		welfare: {
			title: "Welfare Secretary",
			president: "Bithia Panford",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/.jpg",
		},
		awelfare: {
			title: "Assistant Welfare Secretary",
			president: "Lydia Amoaniwaa",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/.jpg",
		},
		organa: {
			title: "Organizing Secretary",
			president: "Kwasi Adu-Bediako",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/.jpg",
		},
		aorgana: {
			title: "Assistant Organizing Secretary",
			president: "Davis Ansah-Boakye",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/davis.jpg",
		},
		fina: {
			title: "Financial Secretary",
			president: "Enoch Tetteh",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/fina.jpg",
		},
		treasurer: {
			title: "Treasurer",
			president: "Benedicta Asi Kubi",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/.jpg",
		},
		advisor: {
			title: "Advisor",
			president: "Suomi Buermley Puplampu",
			level: "600",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/advisor.jpg",
		},
		cordi: {
			title: "Schools' Coordinator",
			president: "Daniella Frimpong",
			level: "400",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/.jpg",
		},
		alumni: {
			title: "Alumni Coordinator",
			president: "Daniel Konadu",
			level: "Completed",
			mainPortfolio: "Name",
			assistantPortfolio: "Level of Study",
			image: "/alumni.jpg",
		},
	},
];

export default coreExecutiveData;
